id: A0AC46E4C
title: 'Music to Delight the Victorious Ones and Their Heirs: A Mahāyāna Aspiration'
type: translation
pechas:
- IECA36101
- IA66F4238
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:07:13.507213
  last_modified_at: 2023-01-04 12:07:13.507217
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IECA36101/E409: 14AF
  IA66F4238/886B: 14AF
